FINANCE_SERVICE_URL_GET_STOCK_PRICE = 'http://127.0.0.1:8001/api/stock_price/'
FINANCE_GET_SPECIFIC_STOCK_PRICE = 'GET_SPECIFIC_STOCK_PRICE'
FINANCE_GET_GENERIC_STOCK_PRICE = 'GET_GENERIC_STOCK_PRICE'
FINANCE_CATEGORY = 'FINANCING'

